### ISSUE TITLE
保存時に走らせるgoimportsでエラーが出る

### ISSUE THREAD

**Issue by jiro4989** [jiro4989/dotfiles#10]
以下のエラーが出力される。
でも一応goimportsは完了しているみたい。

```
Cannot redefine function <SNR>81_exec_goimports: It is in use
```

https://github.com/jiro4989/dotfiles/blob/514b4a557e9a8bac72a0fe34c021147bcfdf39a8/vim/after/ftplugin/go.vim#L48-L59

**Comment by skanehira** [comment]
`:%!goimports` にしたらうまくと思います

**Comment by jiro4989** [comment]
@skanehira 
ありがとうございます。
以下のように修正することで、無事エラーを解消できました :sparkles: 

https://github.com/jiro4989/dotfiles/blob/d3b8868bf1f9f8421890642ca1c85a17bd09c064/vim/after/ftplugin/go.vim#L48-L59

**Comment by skanehira** [comment]
@jiro4989 補足ですが、
上記のコマンドは簡易フィルターなので、もしコマンドエラーがあったらそのまま書き込まれます。
ちゃんとやるならエラーも拾ったほうが良いですが、Undoできるので実用的には問題ないかなと思います。

**Comment by skanehira** [comment]
あ、１点追加
カーソルを完全に復元するなら、次のが良いと思います。

```vim
let pos = getcurpos()
" format
call setpos('.', pos)
```

**Comment by jiro4989** [comment]
@skanehira ありがとうございます。修正しました
